### ISSUE TITLE
Parts label

### ISSUE THREAD

**Issue by antoalli** [hkust-vgd/scanobjectnn#10]
Hi,
From pointnet/train_partseg.py I see that should be an h5 file with part annotated, I'm referring to lines:
parser.add_argument('--train_file', default = '/home/vgd/object_dataset/parts/training_objectdataset_augmented25rot.h5', help='Location of training file')
parser.add_argument('--test_file', default = '/home/vgd/object_dataset/parts/test_objectdataset_augmented25rot.h5', help='Location of test file')
Can't found it, is it available somewhere? Thank you very much!

**Comment by mikacuy** [comment]
Hi,

The experiment shown in the paper is for part segmentation on the chair class. We are tidying up the data at the moment. Please send an email to mikacuy@gmail.com to get an early access to this.
