### ISSUE TITLE
How are the surface normals computed?

### ISSUE THREAD

**Issue by Ryan-Zirui-Wang** [hkust-vgd/scanobjectnn#11]
hi @mikacuy,

Thanks for the paper and dataset. Hope to see it online soon. Can I ask how do you compute surface normals for the dataset? is it using KNN and PCA?

Best,
Zirui

**Comment by mikacuy** [comment]
Hi Zirui,

I used the normals that we're given in the scene reconstruction. I didn't recompute them.

To the best of my knowledge, the normals were estimated from the surface when doing RGB-D fusion, similar to how KinectFusion works.

Best,
Mika

**Comment by Ryan-Zirui-Wang** [comment]
Hi Mika, Thanks a lot for your reply. Got it. Best, Zirui
