### ISSUE TITLE
DGCNN accuracy 

### ISSUE THREAD

**Issue by boweiliu0428** [hkust-vgd/scanobjectnn#12]
Hi,

I have a question about running dgcnn. I ran the code in scanobjectnn/dgcnn/train.py with the default parameters, and the eval accuracy I got stabilized to 0.792. But I see that in the paper (https://hkust-vgd.github.io/scanobjectnn/) the overall accuracy is 0.781, while bga-dgcnn is 0.797. So I am wondering if train.py is running the naive dgcnn, or it is actually running bga-dgcnn?

**Comment by boweiliu0428** [comment]
[log_train.txt](https://github.com/hkust-vgd/scanobjectnn/files/4211692/log_train.txt)

**Comment by mikacuy** [comment]
Hi,

There was no random seed set during training, so there would be some variance in the results. We just ran the model for a fixed number of epochs and took the last checkpoint. Probably, could have done a more thorough evaluation on this. Please also use the evaluation script to evaluate the performance.
