### ISSUE TITLE
Eval Accuracy

### ISSUE THREAD

**Issue by boweiliu0428** [hkust-vgd/scanobjectnn#13]
https://github.com/hkust-vgd/scanobjectnn/blob/fe60aeade9ceb8882bc3f1bc40612e65469d7e77/SpiderCNN/train.py#L264

Hi,

I see that in [method_floder]/train.py the evaluation feeds a fixed batch_size number of pointclouds to the model. However, if `    current_data.shape[0] % BATCH_SIZE != 0
` there are some leftover pointclouds in the evaluation set that are not evaluated. Does this pose a problem for the eval accuracy?

**Comment by mikacuy** [comment]
Hi,

Please use the evaluation script to evaluate and not train.py, and it won't be a problem.

Thanks,
Mika
