### ISSUE TITLE
Number of points in each object

### ISSUE THREAD

**Issue by rabbiahassan** [hkust-vgd/scanobjectnn#15]
Hy !
Number of points in ScanObjectNN dataset are 2048 for each object.
while in modelnet dataset each object of each category has 10,000 points.
Isn't it difficult for network to learn features from such small (2048) points?
I Look forward to your reply.
Thanks

**Comment by mikacuy** [comment]
Hi,

I think that the default .h5 file that is most classification models use for ModelNet40 also has 2048 points per object. (From this download link: https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip)

In each iteration of the network, 1024 points is randomly sampled from the 2048. Usually this is enough for classification from what I've tried.

Thanks,
Mika

**Comment by rabbiahassan** [comment]
Thank you so much for your reply.
You are totally right about 2048 points in .hf version of modelnet you mentioned.
But I was referring to this version of modelnet which has 10,000 points per shape.
it has all txt files.

https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip

Thanks 
Rabbia

**Comment by mikacuy** [comment]
Hi,

I apologize for the delayed response. You can refer to the original .bin files for a denser point cloud. Those contain all the object points that were present in the scene reconstructions. Note that the number of points on each object will not be the same and some might have <10k points.

**Comment by rabbiahassan** [comment]
Thank you very much for the reply.Much appreciated .
