### ISSUE TITLE
About training of pointnet and pointnet++ on modelnet40 dataset

### ISSUE THREAD

**Issue by Emenent758** [hkust-vgd/scanobjectnn#18]
As you mentioned in the paper that pointnet and pointnet++ have been trained on modenet40 and then tested on your dataset. Did you train both pointnet and pointnet++ using all the 40 categories of modelnet40  or just those 11 categories which are overlapping with your dataset?
Thanks
![image](https://user-images.githubusercontent.com/67109198/85029162-6ae72c80-b195-11ea-9c42-fd43c3b791e6.png)

**Comment by mikacuy** [comment]
For Table 3 in the main paper, we used all 40 classes on ModelNet40 for training the models. You may refer to the supplementary material for results on training on the common categories between the two datasets. Thanks!

**Comment by Emenent758** [comment]
Thanks a lot
