### ISSUE TITLE
How to evaluate on scanobjectnn with model trained on ModelNet40?

### ISSUE THREAD

**Issue by usherbob** [hkust-vgd/scanobjectnn#2]
Hello Mikaela,

When I trained my classification model on ModelNet40, how to evaluate on your dataset with 11 common classes? It seems that your `evaluate_scenennobjects.py` is for models trained on your dataset.

**Comment by mikacuy** [comment]
Hi,

I have just added the script for that. Please see the file "evaluate_real_trained_on_synthetic.py". You can see the class mapping file in "mapping2.py".

Documentation of the code will be coming soon. Thanks!

**Comment by usherbob** [comment]
Thanks, just can't wait to learn more about your dataset.
