### ISSUE TITLE
Dataset Name Correspondence.

### ISSUE THREAD

**Issue by usherbob** [hkust-vgd/scanobjectnn#20]
Hi, Mikaela Uy,

  Since I've got your main split data last year, the name of dataset is not perfectly correspondent to your paper. I wonder if there's updating of your dataset and its description. And what is _test_objectdataset_augmentedrot_scale75_newsplit_ for?

**Comment by mikacuy** [comment]
Hi,

augmentedrot_scale75 is PB_T50_RS. The correspondence is the same as written in the README of this repo.

Best,
Mika
