### ISSUE TITLE
Any additional attributes for visualization?

### ISSUE THREAD

**Issue by usherbob** [hkust-vgd/scanobjectnn#21]
Hi, Mikaela Uy,
  
  I wonder how to render the point cloud like pics in your paper, like this.
![image](https://user-images.githubusercontent.com/22768647/88885486-2dcd8a00-d26b-11ea-860c-8b8a686056f2.png)
 I believe we need additional attributes like RGB channels to visualize a point cloud as in your figure. However, the h5 file downloaded from your main split does not have these attributes.

**Comment by mikacuy** [comment]
Hi,

I apologize for the late response. The bin files will have the rgb and other information, you would have to download the raw files for that. Thanks!
