### ISSUE TITLE
Generalization of real vs synthetic

### ISSUE THREAD

**Issue by gaunzi** [hkust-vgd/scanobjectnn#25]
Hi,
I have a confusion about **'4.1 Training on ModelNet40'** in main paper, where indicates 'training is done on ModelNet40 and testing is done on ScanObjectNN ... '. I wonder that when train the networks on ModelNet40, how many classes in training set ? 40 classes in original ModelNet40 dataset or 11 common classes listed in table 1 in Supplementary Materials.
Thanks

**Comment by gaunzi** [comment]
I figure out the problem. Thanks.

**Comment by mikacuy** [comment]
Great!
