### ISSUE TITLE
Could you please share the download link?

### ISSUE THREAD

**Issue by curiosity654** [hkust-vgd/scanobjectnn#29]
Hi there, thanks for your work on the dataset. I have emailed on Jan 13 and Feb 3 but there's no response ever since. So I have to open an issue as a kindly reminder. (I have sent the email again today.)

**Comment by SILI1994** [comment]
@curiosity654 Hi, have you obtained the link?

**Comment by curiosity654** [comment]
> @curiosity654 Hi, have you obtained the link?

Yes, you can directly contact the author by email if you are requesting for the data.
