### ISSUE TITLE
what is the difference between main_split,split1,split2,split3 and split4

### ISSUE THREAD

**Issue by LiDaiY** [hkust-vgd/scanobjectnn#3]
Dear author,
I find there are several folders in h5.zip, but I don't understand what is the difference between them. Did you use  'main_split' as train/test dataset when you did experiments which mentioned in the paper, beacuse I notice you use 'main_split' in the code. Thanks!

**Comment by mikacuy** [comment]
Hi,

Thank you for your interest in our work. "main_split" was used for the experiments in our main paper, while the other splits (1-4) are additional splits that we reported in our supplementary materials.

**Comment by LiDaiY** [comment]
> Hi,
> 
> Thank you for your interest in our work. "main_split" was used for the experiments in our main paper, while the other splits (1-4) are additional splits that we reported in our supplementary materials.

Thank you for your reply！
