### ISSUE TITLE
where could I download the data?

### ISSUE THREAD

**Issue by jiajingchen113322** [hkust-vgd/scanobjectnn#31]
where could I donwload the h5_files.zipped file which contains the data? very appreciate for that if you could share the data. thanks

**Comment by songuke** [comment]
Please use this link: http://103.24.77.34/scanobjectnn/
Thanks.

2021年8月21日(土) 0:25 jiajingchen113322 ***@***.***>:

**Comment by ChenFFCs** [comment]
Do you have data in .ply format?

**Comment by sonhua** [comment]
Please kindly note that the data is moved to this link: http://hkust-vgd.ust.hk/scanobjectnn/
