### ISSUE TITLE
How to render RGB images?

### ISSUE THREAD

**Issue by universome** [hkust-vgd/scanobjectnn#36]
Hi, thank you a lot for your amazing work! I've downloaded the raw files. Could you please tell, how can I render the images from them now similar to the ones which you showed in the teaser:
![objects_teaser](https://user-images.githubusercontent.com/3128824/200420722-9f6c6a7d-f28d-4d79-bab5-42ce5fdc1687.png)

The problem I get is that I do not know the correct camera position, and as a result my images look weird, e.g. (that's an image of a sink which appears to be upside down):
![sink](https://user-images.githubusercontent.com/3128824/200420842-e4ef5472-709d-4c5c-81ee-e0f80cf2e9d3.png)

I used the default dataset without any rotations.
Could you please tell, where did you get the camera parameters from to render the images?

**Comment by songuke** [comment]
Hi Ivan,

For the teaser I have to load the objects into a 3D viewer, rotates them
into a good view, capture the camera parameters of that view and reuse the
camera parameters for other objects.
It should work most of the time except for some objects that might require
adjustments of their own views.

Nowadays I think you can use Open3D to make this viewer and save the
screenshots.


2022年11月8日(火) 4:39 Ivan Skorokhodov ***@***.***>:

**Comment by universome** [comment]
I see, thank you for your help!

**Comment by agoodge** [comment]
Hello @universome , may I ask did you achieve this? I also want to do the same.

**Comment by universome** [comment]
Hi @agoodge , no, sorry, I couldn't automate this.
