### ISSUE TITLE
h5 labels

### ISSUE THREAD

**Issue by antoalli** [hkust-vgd/scanobjectnn#4]
Hi! First of all, thank you for letting me play with this dataset.
I'm currently using the h5 files. Can you confirm me that the label-integer correspondence (in h5 splits) is the one from 'shape_names_ext.txt' in ascending order and starting from zero?
e.g.
{bag: 0, bin: 1, box: 2, cabinet: 3, chair: 4, desk: 5, display: 6, door: 7, shelf: 8, table: 9, bed:	10, pillow: 11, sink:	12, sofa:	13, toile:	14}

**Comment by mikacuy** [comment]
Hi,

Thank you for your interest in our work. Yes, that’s right.
