### ISSUE TITLE
Has the dataset download link been removed?

### ISSUE THREAD

**Issue by liujiaheng** [hkust-vgd/scanobjectnn#9]
Hi, I click the dataset link, but I find the link is empty.
Looking forward to your reply!
Thanks.

**Comment by liujiaheng** [comment]
@mikacuy Hi, could you check the problem of downloading link?

**Comment by mikacuy** [comment]
Hi,

The link is temporarily unavailable. We will release the tool to extract the objects by Friday this week (PST). We apologize for the inconvenience caused.

**Comment by liujiaheng** [comment]
Thanks for your reply. Do you mean that the download link will work this Friday?

**Comment by krips89** [comment]
Hello,
I'm also very much interested in this dataset for comparison. 
I would be really glad if you can make it available (in any format: raw files, tools doesn't matter) as fast as possible. 
Thanks a lot!

**Comment by jackd** [comment]
I'm also pretty keen to get my hands on this - CVPR deadline is looming :S.

**Comment by mikacuy** [comment]
Hi all,

Thank you for your interest in our work.

We are currently tidying up the data for public release, if you need an early access for academic purposes, please send an email to mikacuy@gmail.com.

Thanks,
Mika

**Comment by sheshappanavar** [comment]
@mikacuy I have emailed regarding the dataset. Please provide early access. 
Thanks in advance.

**Comment by JLU-Neal** [comment]
> @mikacuy Hi, could you check the problem of downloading link?

Hey, have you got the link?  Could you please resent it to me? my email: tangzifeng37@yeah.net

**Comment by JLU-Neal** [comment]
> @mikacuy I have emailed regarding the dataset. Please provide early access.
> Thanks in advance.

Hey, have you got the link? Could you please resent it to me? my email: tangzifeng37@yeah.net

**Comment by mikacuy** [comment]
Sent!

**Comment by JLU-Neal** [comment]
> Sent!
Got it! Thanks a lot :100:

**Comment by lykius** [comment]
Hi @mikacuy,

Cheers for creating such a good resource for the 3D community!
We sent you an email requesting the link but we didn't receive any answer, can you please share it with us?

Thanks in advance!!
